In [1]:
import numpy as np 
# sigmoid function 
def sig(x):
    return (1/(1+np.exp(-x))) 
def deridig(y):
    return y*(1-y) 
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
# output dataset
y = np.array([[0,0,1,1]]).T
#
np.random.seed(1)
 
# initialize weights randomly with mean 0
w0 = 2*np.random.random((3,1)) - 1
b0=1
lr=1
for iter in range(10000):
    # forward propagation
    l0 = X
    l1 = sig(np.dot(l0,w0)+b0)
    E_error=(y-l1)*(y-l1)
    # update weights
    #每次调整的幅度可自行设定
    w0 += 1*np.dot(l0.T,2*(y-l1) *deridig(l1))
    b0 += 1*2*(y-l1) *deridig(l1)
    #print ('w0',w0)
    
print ("Output After Training:")
print (l1)
print ("w0 After Training:")
print (w0)
print ("b0 After Training:")
print (b0)


Output After Training:
[[0.00411501]
 [0.00384688]
 [0.99675082]
 [0.99643784]]
w0 After Training:
[[ 5.05661648]
 [-0.2814999 ]
 [-2.84714308]]
b0 After Training:
[[-2.64189825]
 [-2.42804605]
 [ 3.51667531]
 [ 3.70589715]]


In [11]:
from numpy import exp, array, random, dot
class NeuralNetwork():
    def __init__(self):
        # Seed the random number generator, so it generates the same numbers
        self.synaptic_weights = 2 * random.random((3, 1)) - 1

    # The Sigmoid function, which describes an S shaped curve.
    def __sigmoid(self, x):
        return 1 / (1 + exp(-x))

    # The derivative of the Sigmoid function.    
    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    # train the neural network through a process of trial and error.Adjusting the synaptic weights each time.
    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in range(number_of_training_iterations):
            # Pass the training set through our neural network (a single neuron).
            output = self.think(training_set_inputs)
            # Calculate the error
            error = training_set_outputs - output
            # Multiply the error by the input and again by the gradient of the Sigmoid curve.
            adjustment = dot(training_set_inputs.T, error * self.\
__sigmoid_derivative(output))
            # Adjust the weights.
            self.synaptic_weights += adjustment
    # The neural network thinks.
    def think(self, inputs):
        # Pass inputs through our neural network (our single neuron).
        return self.__sigmoid(dot(inputs, self.synaptic_weights));
if __name__ == "__main__":
    neural_network = NeuralNetwork()
    print("Random starting synaptic weights: ")
    print(neural_network.synaptic_weights)
    # dataset has 3 input values and 1 output value.
    training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
    training_set_outputs = array([[0, 1, 1, 0]]).T

    # Train the neural network 10,000 times,make small adjustments each time.
    neural_network.train(training_set_inputs, training_set_outputs, 10000)

    print ("New synaptic weights after training: ")
    print( neural_network.synaptic_weights)

    # Test the neural network with a new situation.
    print ("Considering new situation [1, 0, 0] ->?: ")
    print (neural_network.think(array([1, 0, 0])))


Random starting synaptic weights: 
[[ 0.93652315]
 [-0.37315164]
 [ 0.38464523]]
New synaptic weights after training: 
[[ 9.67320723]
 [-0.20879939]
 [-4.62917369]]
Considering new situation [1, 0, 0] ->?: 
[0.99993706]
